baseurl = "http://www.lucabol.com"
languageCode = "en-us"
title = "Lucabol blog"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"
enableGitInfo = true
enableRobotsTXT = true

disqusShortname = "lucabol"

relativeURLs = true

# Removes categories taxonomy
[taxonomies]
  tag = "tags"

# Code highlighting, see here for style https://xyproto.github.io/splash/docs/longer/all.html
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "vs"

[permalinks]
    posts = "/:year/:month/:day/:title/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
[[menu.main]]
    name = "Github"
    url = "http://www.github.com/lucabol"
    weight = 3
[[menu.main]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/lucabolognese/"
    weight = 4

[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "Blog about programming, C#, F#, .NET Core, Investing and other stuff."
    #footer = "[Github](https://github.com/lucabol)"
    custom_css = ["css/theme-override.css"]
    toc = true