baseurl = "https://www.lucabol.com"
languageCode = "en-us"
title = "Lucabol blog"
theme = "hugo-classic"
googleAnalytics = "UA-133194891-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"
enableGitInfo = true
enableRobotsTXT = true

disqusShortname = "lucabol"

relativeURLs = true

# Code highlighting, see here for style https://xyproto.github.io/splash/docs/longer/all.html
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "vs"

# Removes categories taxonomy
[taxonomies]
  tag = "tags"

# json is to enable search index build
[outputs]
  home = ["HTML", "RSS", "JSON"]

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
[[menu.main]]
    name = "Github"
    url = "https://www.github.com/lucabol"
    weight = 3
[[menu.main]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/lucabolognese/"
    weight = 4

[[menu.feed]]
    name = "Search"
    url = "/search"
    weight = 2

[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"
    weight = 1

[params]
    description = "Blog about programming, C#, F#, .NET Core, Investing and other stuff."
    toc = true